if filereadable(expand("~/vim/vimrc"))
  source ~/dotfiles/vim/vimrc.plugins
endif
"
if filereadable(expand("~/dotfiles/vim/vimrc.local"))
    source ~/dotfiles/vim/vimrc.local
endif

if filereadable(expand("~/dotfiles/vim/vimrc.keymap"))
  source ~/dotfiles/vim/vimrc.keymap
endif